<?php include __DIR__ . '/../layout/header.phtml'; ?>

<h2>Login de Administrador</h2>

<form action="<?= BASE_URL ?>do_login" method="POST" class="mt-3">
    <label>Usuario:</label>
    <input type="text" name="user" required>
    <label>Contraseña:</label>
    <input type="password" name="password" required>
    <button type="submit" class="btn btn-primary mt-2">Ingresar</button>
</form>

<?php if (!empty($error)) echo "<p style='color:red'>$error</p>"; ?>
